# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Python 101
author: "<a href='https://sahilchoudhary.com/'>Sahil Choudhary</a> "
logo: logo1.PNG
page_authors: false
# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/hksahil/Python-101  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)



launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  thebe                  : true

#######################################################################################
# HTML-specific settings
html:
  google_analytics_id: UA-192065875-1
  use_issues_button: true
  #use_repository_button: true
  use_multitoc_numbering: false
 # extra_footer:
  extra_navbar: <p>  </p>     
  extra_footer:
    <p>
        <a href="https://www.buymeacoffee.com/hksahil"><img src="https://img.shields.io/badge/Buy_Me_A_Coffee-FFDD00?style=for-the-badge&logo=buy-me-a-coffee&logoColor=black" alt="Be me a coffee"></a>
        <a href="https://github.com/hksahil/Python-101"><img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="Github"></a>
    </p>
  comments:
    utterances:
      repo: "hksahil/Python-101"
sphinx:
  config:
    html_show_copyright: false
    html_extra_path: ['_static']
    #html_js_files: https://buttons.github.io/buttons.js
